server {
    listen 80;
    index index.php index.html;
    server_name intra-youcode.me;
    root /var/www/public;

    # 1. FRONTEND : On redirige tout vers le serveur Vite
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 2. BACKEND : On laisse les routes /api et /sanctum aller vers Laravel
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /sanctum {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 3. Traitement PHP (Backend)
    location ~ \.php$ {
<<<<<<< HEAD
=======
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
>>>>>>> 60b6f74 (change)
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
